config/routes.rb
T::Application.routes.draw do

  resources :quizzes

  post '/solve/:id' => 'quizzes#solve'

  root to: 'quizzes#home'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :solve]
  before_filter :authorize, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  def home
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.as.build
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to action: 'edit', id: @quiz.id, notice: 'Quiz was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quiz }
      else
        format.html { render action: 'new' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to action: 'edit', id: @quiz.id, notice: 'Quiz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url }
      format.json { head :no_content }
    end
  end


  def solve
    render json: @quiz.find_answer(params[:results].collect{ |i| i.to_i })
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(
        :title, 
        :text, 
        :img,

        as_attributes:[
          :id,
          :img, 
          :code, 
          :title, 
          :text,
          :quiz_id, 
          :_destroy
        ],

        qs_attributes:[
          :id, 
          :order, 
          :title, 
          :quiz_id, 
          :_destroy,

          options_attributes:[
            :id, 
            :q_id, 
            :text, 
            :code, 
            :_destroy
          ]
      ])
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.slim
.row
  .col-lg-6
    = nested_form_for @quiz do |f|
      .row
        .field.col-lg-4
          = f.label :title
          = f.text_field :title, class: "form-control"
        .field.col-lg-4
          = f.label :text
          = f.text_field :text, class: "form-control"
      .row
        .field.col-lg-4
          = f.label :img
          = f.file_field :img, class: "form-control"
        .field.col-lg-4
          = image_tag @quiz.img.url

      .row 
        .col-lg-12
          br 
          h2 Questions:
          hr
      = f.fields_for :qs do |q|
        .row
          .field.col-lg-4
            = q.label :title
            = q.text_field :title, class: "form-control"
          .field.col-lg-4
            = q.label :order
            = q.number_field :order, class: "form-control"
          .col-lg-3.col-lg-offset-1
            = q.link_to_remove "Remove this question"

        .row
          .col-lg-12
            .row
              .col-lg-2
                br
                h4 Options:
            .row style='font-size: 11px'
              .col-lg-12
                = q.fields_for :options do |option|
                  .row
                    .col-lg-4
                      .field
                        = option.label :text
                        = option.text_field :text, class: "form-control"
                    .col-lg-4
                      .field
                        = option.label :code
                        = option.number_field :code, class: "form-control"
                    .col-lg-3.col-lg-offset-1
                      = option.link_to_remove "Remove this option"
            = q.link_to_add "Add option", :options
        hr


      = f.link_to_add "Add question", :qs
      br
      hr

      .row 
        .col-lg-12
          br 
          h2 Answers:
          hr

      - @quiz.as.each do |answer|
        = f.fields_for :as, answer do |a|
          .row
            .field.col-lg-4
              = a.label :img
              = a.file_field :img, class: "form-control"
            .col-lg-4
              - if answer.img_file_size.present?
                = image_tag answer.img, width: 100, height: 100
            .col-lg-3.pull-right 
              = a.link_to_remove "Remove this answer"
          .row
            .field.col-lg-4
              = a.label :title
              = a.text_field:title, class: "form-control"
            .field.col-lg-4
              = a.label :code
              = a.number_field :code, class: "form-control"
          .row
            .field.col-lg-4
              = a.label :text
              = a.text_area :text, class: "form-control"
          hr


      = f.link_to_add "Add answer", :as
      hr

      .actions 
        = f.submit 'Save', class: 'btn btn-primary btn-block btn-lg'

app/views/quizzes/edit.html.slim
.header
  .row
    .col-lg-6
      h1 Editing quiz
      hr

== render 'form'

.footer
  .row
    .col-lg-6= link_to 'Back', quizzes_path, class: 'btn btn-info btn-block btn-lg'
    br/
    .col-lg-6= link_to 'All quizzes', root_path, class: 'btn btn-info btn-block btn-lg'

app/views/quizzes/home.html.slim
.demo-headline
  .demo-logo
    =image_tag 'icons/png/Clipboard.png'
    | Quizz!
.row
  - @quizzes.each do |q|
    .col-xs-3
      .tile
        =image_tag q.img.url, class: 'tile-image big-illustration'
        h3.tile-title =q.title
        p=q.text
        =link_to 'Start quiz!', q, class: 'btn bt-block btn-embosed btn-large btn-default'

app/views/quizzes/index.html.slim
.row
  .col-lg-6
    h1 Listing quizzes
    br

    table.table
      thead
        tr
          th id
          th Image
          th Title
          th Text
          th Questions
          th
          th
          th

      tbody
        - @quizzes.each do |quiz|
          tr
            td = quiz.id
            td = image_tag quiz.img.url, height: "100", width: "100"
            td = quiz.title
            td = quiz.text
            td
              - quiz.qs.each do |q|
                ul
                  li=q.title
            td
              = link_to 'Show', quiz
            td
              = link_to 'Edit', edit_quiz_path(quiz)
            td
              = link_to 'Destroy', quiz, data: {:confirm => 'Are you sure?'}, :method => :delete
      br

    .row
      = link_to 'New Quiz', new_quiz_path, class: 'btn btn-lg btn-block btn-info'
      br/
      = link_to 'All quizzes', root_path, class: 'btn btn-lg btn-block btn-info'

app/views/quizzes/new.html.slim
.header
  .row
    .col-lg-6
      h1 New quiz
      hr

== render 'form'

.footer
  .row
    .col-lg-6= link_to 'Back', quizzes_path, class: 'btn btn-info btn-block btn-lg'
   